version: 2.1

jobs:
  configure_infrastructure:
    docker:
      - image: python:3.7-alpine3.16
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints: ["f8:b2:7a:11:71:ad:6b:b5:64:94:96:f9:d5:7c:aa:3a"]
      - run:
          name: "Install Ansible"
          command: |
            apk add --update ansible
      - run:
          name: "Run Playbook and Configure server"
          command: |
            ansible-playbook main.yml -i inventory

workflows:
  infra-workflow:
    jobs:
      - configure_infrastructure
