version: 2.1

jobs:
  configure_infrastructure:
    docker:
      - image: python:3.7-alpine3.11
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints: ["6a:68:59:e7:24:78:0b:55:82:57:2a:f8:35:d7:14:ac"]
      - run:
          name: "Install Ansible"
          command: |
            apk add --update ansible ssh
      - run:
          name: "Run Playbook and Configure server"
          command: |
            ansible-playbook main.yml -i inventory

workflows:
  infra-workflow:
    jobs:
      - configure_infrastructure
