version: 2.1

jobs:
  configure_infrastructure:
    docker:
      - image: python:3.7-alpine3.11
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints: ["5d:7c:3b:82:f3:3b:62:3d:df:09:16:55:25:8e:d3:0a"]
      - run:
          name: "Install Ansible"
          command: |
            apk add --update ansible
      - run:
          name: "Run Playbook and Configure server"
          command: |
            ansible-playbook -i inventory.txt ansible-main.yml

workflows:
  infra-workflow:
    jobs:
      - create_infrastructure
